server:
  port: 9090
  error:
    path: error.jsp

spring:
  application:
    name: demo
  data:
    mongodb:
      uri: mongodb+srv://*****:*****:@******.******.******.******/?retryWrites=******&w=******&appName=******
      database: ******
  mail:
    host: smtp.gmail.com
    port: 587
    username: ******@gmail.com
    password: ******
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


